export { default as NewsSection } from "./news-section";
export { default as SocialSection } from "./social-section";
export { default as CategoriesSection } from "./categories-section";
export { default as SubscribeSection } from "./subscribe-section";
export { default as FamousSection } from "./famous-section";
export { default as PromotionSection } from "./promotion-section";
export { default as PartnersSection } from "./partners-section";
export { default as WhySection } from "./why-section";
export { default as Advantages } from './advantages'
export { default as Description } from './description'
export { default as Follow } from './follow'
